package com.demo.entities;
// Generated Nov 16, 2023, 12:36:49 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien", catalog = "onlinehelpdesk")
public class Nhanvien implements java.io.Serializable {

	private String username;
	private Quyen quyen;
	private String password;
	private String hoten;
	@DateTimeFormat(pattern ="yyyy-MM-dd")
	private Date ngaysinh;
	private String kichhoat;
	private String hinhanh;
	private Set<Yeucau> yeucausForManvGui = new HashSet<Yeucau>(0);
	private Set<Yeucau> yeucausForManvXuly = new HashSet<Yeucau>(0);

	public Nhanvien() {
	}

	public Nhanvien(String username, Quyen quyen, String password, String hoten, Date ngaysinh, String kichhoat,
			String hinhanh) {
		this.username = username;
		this.quyen = quyen;
		this.password = password;
		this.hoten = hoten;
		this.ngaysinh = ngaysinh;
		this.kichhoat = kichhoat;
		this.hinhanh = hinhanh;
	}

	public Nhanvien(String username, Quyen quyen, String password, String hoten, Date ngaysinh, String kichhoat,
			String hinhanh, Set<Yeucau> yeucausForManvGui, Set<Yeucau> yeucausForManvXuly) {
		this.username = username;
		this.quyen = quyen;
		this.password = password;
		this.hoten = hoten;
		this.ngaysinh = ngaysinh;
		this.kichhoat = kichhoat;
		this.hinhanh = hinhanh;
		this.yeucausForManvGui = yeucausForManvGui;
		this.yeucausForManvXuly = yeucausForManvXuly;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 250)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quyen", nullable = false)
	public Quyen getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Quyen quyen) {
		this.quyen = quyen;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "hoten", nullable = false, length = 250)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaysinh", nullable = false, length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "kichhoat", nullable = false, length = 250)
	public String getKichhoat() {
		return this.kichhoat;
	}

	public void setKichhoat(String kichhoat) {
		this.kichhoat = kichhoat;
	}

	@Column(name = "hinhanh", nullable = false, length = 250)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByManvGui")
	public Set<Yeucau> getYeucausForManvGui() {
		return this.yeucausForManvGui;
	}

	public void setYeucausForManvGui(Set<Yeucau> yeucausForManvGui) {
		this.yeucausForManvGui = yeucausForManvGui;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvienByManvXuly")
	public Set<Yeucau> getYeucausForManvXuly() {
		return this.yeucausForManvXuly;
	}

	public void setYeucausForManvXuly(Set<Yeucau> yeucausForManvXuly) {
		this.yeucausForManvXuly = yeucausForManvXuly;
	}

}
