package com.demo.entities;
// Generated Nov 16, 2023, 12:36:49 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Quyen generated by hbm2java
 */
@Entity
@Table(name = "quyen", catalog = "onlinehelpdesk")
public class Quyen implements java.io.Serializable {

	private Integer marole;
	private String tenrole;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

	public Quyen() {
	}

	public Quyen(String tenrole) {
		this.tenrole = tenrole;
	}

	public Quyen(String tenrole, Set<Nhanvien> nhanviens) {
		this.tenrole = tenrole;
		this.nhanviens = nhanviens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "marole", unique = true, nullable = false)
	public Integer getMarole() {
		return this.marole;
	}

	public void setMarole(Integer marole) {
		this.marole = marole;
	}

	@Column(name = "tenrole", nullable = false, length = 250)
	public String getTenrole() {
		return this.tenrole;
	}

	public void setTenrole(String tenrole) {
		this.tenrole = tenrole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyen")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

}
