package com.demo.entities;
// Generated Nov 16, 2023, 12:36:49 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * Yeucau generated by hbm2java
 */
@Entity
@Table(name = "yeucau", catalog = "onlinehelpdesk")
public class Yeucau implements java.io.Serializable {

	private Integer mayeucau;
	private Douutien douutien;
	private Nhanvien nhanvienByManvGui;
	private Nhanvien nhanvienByManvXuly;
	private String tieude;
	private String noidung;
	private Date ngaygui;

	public Yeucau() {
	}

	public Yeucau(Douutien douutien, Nhanvien nhanvienByManvGui, String tieude, String noidung, Date ngaygui) {
		this.douutien = douutien;
		this.nhanvienByManvGui = nhanvienByManvGui;
		this.tieude = tieude;
		this.noidung = noidung;
		this.ngaygui = ngaygui;
	}

	public Yeucau(Douutien douutien, Nhanvien nhanvienByManvGui, Nhanvien nhanvienByManvXuly, String tieude,
			String noidung, Date ngaygui) {
		this.douutien = douutien;
		this.nhanvienByManvGui = nhanvienByManvGui;
		this.nhanvienByManvXuly = nhanvienByManvXuly;
		this.tieude = tieude;
		this.noidung = noidung;
		this.ngaygui = ngaygui;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "mayeucau", unique = true, nullable = false)
	public Integer getMayeucau() {
		return this.mayeucau;
	}

	public void setMayeucau(Integer mayeucau) {
		this.mayeucau = mayeucau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "madouutien", nullable = false)
	public Douutien getDouutien() {
		return this.douutien;
	}

	public void setDouutien(Douutien douutien) {
		this.douutien = douutien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manv_gui", nullable = false)
	public Nhanvien getNhanvienByManvGui() {
		return this.nhanvienByManvGui;
	}

	public void setNhanvienByManvGui(Nhanvien nhanvienByManvGui) {
		this.nhanvienByManvGui = nhanvienByManvGui;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manv_xuly")
	public Nhanvien getNhanvienByManvXuly() {
		return this.nhanvienByManvXuly;
	}

	public void setNhanvienByManvXuly(Nhanvien nhanvienByManvXuly) {
		this.nhanvienByManvXuly = nhanvienByManvXuly;
	}

	@Column(name = "tieude", nullable = false, length = 250)
	public String getTieude() {
		return this.tieude;
	}

	public void setTieude(String tieude) {
		this.tieude = tieude;
	}

	@Column(name = "noidung", nullable = false, length = 65535)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaygui", nullable = false, length = 10)
	public Date getNgaygui() {
		return this.ngaygui;
	}

	public void setNgaygui(Date ngaygui) {
		this.ngaygui = ngaygui;
	}

}
