package com.demo.entities;
// Generated Aug 18, 2023, 2:33:02 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * InvoiceDetails generated by hbm2java
 */
@Entity
@Table(name = "invoice_details")
public class InvoiceDetails implements java.io.Serializable {

	private InvoiceDetailsId id;
	private Invoice invoice;
	private Product product;
	private int quantity;
	private double price;

	public InvoiceDetails() {
	}

	public InvoiceDetails(InvoiceDetailsId id, Invoice invoice, Product product, int quantity, double price) {
		this.id = id;
		this.invoice = invoice;
		this.product = product;
		this.quantity = quantity;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceId", column = @Column(name = "invoice_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public InvoiceDetailsId getId() {
		return this.id;
	}

	public void setId(InvoiceDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id", nullable = false, insertable = false, updatable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
