package com.demo.entities;
// Generated Oct 27, 2023, 12:26:32 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language implements java.io.Serializable {

	private Integer id;
	private String languageId;
	private String countryId;
	private String flag;
	private String name;
	private Set<ProductLanguage> productLanguages = new HashSet<ProductLanguage>(0);

	public Language() {
	}

	public Language(String languageId, String countryId, String flag, String name) {
		this.languageId = languageId;
		this.countryId = countryId;
		this.flag = flag;
		this.name = name;
	}

	public Language(String languageId, String countryId, String flag, String name,
			Set<ProductLanguage> productLanguages) {
		this.languageId = languageId;
		this.countryId = countryId;
		this.flag = flag;
		this.name = name;
		this.productLanguages = productLanguages;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "language_id", nullable = false, length = 10)
	public String getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(String languageId) {
		this.languageId = languageId;
	}

	@Column(name = "country_id", nullable = false, length = 10)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "flag", nullable = false, length = 250)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<ProductLanguage> getProductLanguages() {
		return this.productLanguages;
	}

	public void setProductLanguages(Set<ProductLanguage> productLanguages) {
		this.productLanguages = productLanguages;
	}

}
